Update Info.astro
midudev/la-velada-web-oficial pull request #36
Opened 2024-02-21 20:47 UTC by Danehue

se modifico el h4 "síguelo en directo twitch.tv/ibai" para colorear unicamente el enlace a twitch

2024-02-21 22:04 UTC, josealvaradoo requested changes
Ya tenemos un color para twitch en la configuración de tailwind, intenta usar ese, o agrega uno nuevo a la configuración para no tener colores hexadecimales regados por todas partes.

2024-02-21 22:04 UTC, josealvaradoo commented on src/sections/Info.astro
> +    color: #62409f;
¿Este color de donde viene? Ya tenemos un color para twitch y recomiendo hacer uso de [la clase de tailwind](https://github.com/midudev/la-velada-web-oficial/blob/32ffc874d617dae6adbe4e7949f1bb6bc1092703/tailwind.config.mjs#L11) para ello.

2024-02-21 22:04 UTC, josealvaradoo commented on src/sections/Info.astro
> +          Síguelo en directo <span>twitch.tv/ibai</span>
```
<span class="text-twitch">twitch.tv/ibai</span>
```
Basados en el color de twtich que tenemos en [tailwind.config.mjs](https://github.com/midudev/la-velada-web-oficial/blob/32ffc874d617dae6adbe4e7949f1bb6bc1092703/tailwind.config.mjs#L11)

2024-02-23 09:17 UTC, midudev commented
¡Gracias por la PR! Ya se han fusionado cambios similares así que vamos a cerrar esta.

2024-02-23 09:17 UTC, closed without merging