/.husky/pre-commit for webstorm and intellj idles (Ej: webstorm)
midudev/la-velada-web-oficial pull request #796
Opened 2024-03-28 15:33 UTC by MattEzekiel

## Descripción

Agregué unas lineas de código para poder hacer commits desde otro editor de texto como WebStorm

## Problema solucionado

No permitia hacer commits desde otro editor de texto que no sea visual studio code

## Cambios propuestos

```bash
# add this to ~/.huskyrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

## Comprobación de cambios

- [x] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [x] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [ ] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
- [x] He actualizado la documentación, si corresponde.

## Enlaces útiles

- Documentación del proyecto: [Husky](https://github.com/typicode/husky)
- Código de referencia: [referencia](https://github.com/typicode/husky/issues/540)

2024-03-28 17:52 UTC, MattEzekiel commented
@SeanLuis usas algún plugin en particular para webstorm? A mí ni con GitHub cli ni del mismo webstorm me dejaba hacer commits

2024-03-30 05:52 UTC, AlejandroSuero commented
Yo probé desde NeoVim (mi editor habitual), VSCode y desde herramientas como lazygit, Github Desktop y la UI de VSCode. No he tenido problemas desde ninguno.

Si tienes que añadir `nvm`, probablemente sea o un problema de instalación de tu editor por alguna razón, o lo más posible, que tu instalación de `nvm` no se esté llamando desde tu terminal.

2024-03-30 14:01 UTC, MattEzekiel commented
> Yo probé desde NeoVim (mi editor habitual), VSCode y desde herramientas como lazygit, Github Desktop y la UI de VSCode. No he tenido problemas desde ninguno.

Bueno desde githubdesktop tampoco me ha dejado hacer commits, por eso he utilizado el editor de webstorm... Pero con esta PR es la única manera en la que pude hacer commits y además respetar la configuración de husky

2024-03-30 14:41 UTC, AlejandroSuero commented
> @AlejandroSuero
> 
> > Yo probé desde NeoVim (mi editor habitual), VSCode y desde herramientas como lazygit, Github Desktop y la UI de VSCode. No he tenido problemas desde ninguno.
> 
> Bueno desde githubdesktop tampoco me ha dejado hacer commits, por eso he utilizado el editor de webstorm... Pero con esta PR es la única manera en la que pude hacer commits y además respetar la configuración de husky

Desde qué sistema operativo estás trabajando? Para ver si lo puedo recrear e intentar ver el problema.

2024-03-31 03:29 UTC, AlejandroSuero commented
He estado probando en WebStorm desde Windows y Mac, y este es el resultado.

![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/315ad2a2-0056-464f-ae26-f7d3b15938ba)

![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/a2a49812-d327-4a98-afd6-516073e2c8d6)

Por si puedes agregar tu una imagen parecida para ver el problema.

2024-03-31 03:44 UTC, MattEzekiel commented
Github CLI windows 10:
![image](https://github.com/midudev/la-velada-web-oficial/assets/50919956/7e6341d8-e6ca-4417-b350-ceaa2ce2f21e)

Webstorm:
![image](https://github.com/midudev/la-velada-web-oficial/assets/50919956/3f298403-2ea3-49f2-b472-84cd4cea4b08)

El cambio:
![image](https://github.com/midudev/la-velada-web-oficial/assets/50919956/b6ffe317-7d5c-4adb-be37-2493f68c2202)


Por cierto tambíen marca estos errores:
![image](https://github.com/midudev/la-velada-web-oficial/assets/50919956/fa897792-0d06-41aa-a949-0cddc79c942b)

2024-03-31 05:23 UTC, AlejandroSuero commented
@MattEzekiel voy a descargarme un Windows 10 para probar.

En la primera imagen, qué wsl estás usando y qué distribución, para descargarlos también. Y cómo estás abriendo Github Desktop desde wsl.

En la imagen de WebStorm, parece que `lint-staged` está funcionando correctamente.

En la imagen de los errores, no sé por qué está dando ese error, si todos usamos lo mismo. Es tu versión de Node la misma que el proyecto? Si lo es y has `pnpm install` o `npm install`, prueba a borrar el directorio y clonarlo de nuevo, a ver si ha habido alguna configuración que se haya roto por alguna razón.

Desde la terminal te deja hacer el commit o tienes el mismo error? Qué shell (bash, zsh, fish, pwsh, cmd ...) estás usando?

2024-03-31 23:38 UTC, AlejandroSuero commented
@MattEzekiel he hecho unas pruebas, aquí las capturas.

Desde Ubuntu (wsl2) instalación limpia de Windows11 (no puedo emular el 10 desde mac m1).

He probado con la instalación limpia, y con la que tengo en mi PC. También he comprobado en máquinas virtuales con Linux (Ubuntu y Debian) y con un portátil viejo al que he instalado Manjaro (ArchLinux).

Los resultados han sido los mismos a estos:

- Terminal/NeoVim:
![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/3ea3201c-9ac3-4a5c-9edf-8d671d76a7b5)

> [!important]
> `gh repo clone MattEzekiel/la-velada-web-oficial`
> `nvm use`
> `pnpm install`

![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/38f360ad-e584-4576-a673-b2dcc702c18b)

> [!note]
> Mismo cambio en el mismo archivo

![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/632e5138-816f-4561-901d-98682d52f5dd)

> [!important]
> Sin errores de husky pre-commit o lint-staged

- WebStorm:
![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/14af223e-1771-4c62-9799-dbf0fa1f3345)

> [!important]
> `npm install` desde WebStorm, haciendo click en el diálogo que pregunta si hacerlo.

![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/9cbe5cc5-0c5a-41b1-83f9-96b0bee73748)

> [!note]
> Mismo cambio en el mismo archivo

![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/f7579c4b-b725-4197-8300-d920b6175da0)

> [!important]
> Sin errores de husky pre-commit o lint-staged

- Github Desktop:
![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/6c52dbfd-9e0f-4b2e-8e7d-f00eaae08e83)

![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/77ab77d7-117e-48f1-9306-485cbf314926)

> [!important]
> Sin errores de husky pre-commit o lint-staged

- Versiones y configuraciones:
  - Git: git version 2.42.0.windows.2
    ```gitconfig
    [user]
	  name = nombre
	  email = correo
    [core]
	  editor = nvim
      autocrlf = false
    [sequence]
	  editor = nvim
    [safe]
	  directory = C:/ruta/al/directorio/MattEzekiel/la-velada-web-oficial
    [filter "lfs"]
	  required = true
	  clean = git-lfs clean -- %f
	  smudge = git-lfs smudge -- %f
	  process = git-lfs filter-process
    ```
   - nvm: version 1.1.11 en Windows
     ```bash
     # .bashrc / .zshrc
     # nvm version 0.39.7
     # ...
     export NVM_DIR="$HOME/.nvm"
     [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
     [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
     # ...
     ```
> [!note]
> Mis [.dotfiles](https://github.com/AlejandroSuero/.dotfiles/) por si los quieres en más detalles.

Creo que tu problema está en tu configuración. Comprueba que la tengas correctamente, que tienes node instalado, que manejador de node tienes si usas, la version de node del proyecto instalado y usada cuando manejas el repositorio.

Si utilizas wsl, que sea wsl2. Que tu Linux tenga en su archivo de la `shell` (`.bashrc` para bash, `.zshrc` para zsh ...) y que uses la carga de nvm si lo usas, que es lo que estás haciendo que haga husky con esta PR.

2024-04-01 22:04 UTC, AlejandroSuero requested changes

2024-04-01 22:04 UTC, AlejandroSuero commented on .husky/pre-commit
> +
Esto no es lo recomendado en la [versión 9 de husky](https://github.com/typicode/husky/releases/tag/v9.0.1), que es la que estamos utilizando.

Intenta hacer lo con las soluciones propuestas en la [documentación oficial](https://typicode.github.io/husky/troubleshoot.html).

2024-04-01 22:04 UTC, AlejandroSuero commented on .huskyrc
> +}
Esto no es lo recomendado en la [versión 9 de husky](https://github.com/typicode/husky/releases/tag/v9.0.1), que es la que estamos utilizando.

Intenta hacer lo con las soluciones propuestas en la [documentación oficial](https://typicode.github.io/husky/troubleshoot.html).

2024-04-01 22:15 UTC, AlejandroSuero commented
Un cambio que si podrías hacer es crear una `github action` para no usar husky en el proyecto.

Pero eso sería crear una issue y hacer un PR con la propuesta y ver si se aprueba. Ya que sería una `action` más y el encargado del repo es @midudev.

Vídeo de midu al respecto:
<a title="Vídeo de midu sobre Github actions" href="https://www.youtube.com/watch?v=sIhm4YOMK6Q" rel="noopener noreferrer" target="_blank">
  <img src="https://i.ytimg.com/vi/sIhm4YOMK6Q/maxresdefault.jpg" alt="Vídeo de midu sobre Github actions" />
</a>

2024-04-03 16:49 UTC, MattEzekiel commented
Bien, ya he logrado hacer commits desde ambos, tanto webstrom como por github desktop con esta linea de código:
`npx.cmd lint-staged`
Ahora siendo que cmd es algo de windows @AlejandroSuero necesitaría si se puede corroborar que funcione en otras distribuciones

2024-04-03 16:50 UTC, MattEzekiel commented
Si este paso ya no funciona, entonces si, probaría con una github action

2024-04-03 18:46 UTC, AlejandroSuero commented
@MattEzekiel desde MacOS y Linux, no funciona.

<img width="861" alt="husky failing on MacOSX" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/ec0abd6f-6b31-4e1c-92c1-62586a3ade4d">

Tienes que tener algún problema con tu instalación de Node en Windows seguramente, porque al resto nos funciona. No te funciona de ninguna manera usando wsl con Ubuntu mismo? Webstorm no sé como funcionará pero VSCode al menos puedes trabajar desde wsl al igual que desde la máquina principal.

Pero prueba a hacer la github action a ver que tal funciona así.

2024-04-03 18:50 UTC, AlejandroSuero commented
Comprueba que tienes `node` instalado correctamente, verificando las variables de entorno.

Haz `which node` y si no coincide con el `nvm root` si usas `nvm` desinstala Node y haz `nvm root "C:\Program File (x86)\Node"` y `nvm install 18` `nvm use 18`.

Yo tuve que hacer algo parecido porque tenía una aplicación (starship) instalada con `winget` y `scoop` al mismo tiempo y daba fallos a la hora de usarla y actualizarla.

2024-04-03 18:56 UTC, AlejandroSuero commented
![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/e7b71f93-1124-4633-8dea-86c1ec9c7db8)

En la variable de entorno PATH:

![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/376b71b7-ea28-407e-9190-ddfa563f9675)

2024-04-03 19:35 UTC, AlejandroSuero commented
@MattEzekiel He probado el commit https://github.com/midudev/la-velada-web-oficial/pull/796/commits/f03a473d9a1223d193b8fb095719b4d863b49406 MacOSX, Ubuntu y Windows.

Funciona en todos, pero en Ubuntu me sale esto:

![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/25ef2ca3-d125-43a8-b01a-5cad63e5b0cf)

2024-04-03 19:39 UTC, MattEzekiel commented
@AlejandroSuero que raro lo de permission denied... Investigaré un poco más

2024-04-03 19:43 UTC, AlejandroSuero commented
> @AlejandroSuero que raro lo de permission denied... Investigaré un poco más

Lo sé, no debería pasar en teoría porque no se está ejecutando nada que necesite permisos.

2024-04-03 19:46 UTC, AlejandroSuero approved these changes
Cuando esté todo funcionando, crea una nueva PR con los cambios y cierra esta para no subir cambios a `@/consts/event-date.ts` y `@/pages/api/votes/[combatId].ts`

2024-04-04 13:32 UTC, closed without merging

2024-04-12 14:42 UTC, StCost commented on .husky/pre-commit
> +
webstorm won't pass hooks, this code added to pre-commit fixed my issue