fix(#865): not playing when changing combat
midudev/la-velada-web-oficial pull request #866
Opened 2024-04-05 19:23 UTC by AlejandroSuero

## Descripción

Soluciono un bug que introduje en #849

## Problema solucionado

El vídeo no se reproducía al cambiar de combate #865.

## Cambios propuestos

1. Añadir `autoplay` en la etiqueta `video`.

## Capturas de pantalla (si corresponde)

## Comprobación de cambios

- [X] He revisado que no haya ninguna PR (pull request) ya abierta con un problema similar, siguiendo el apartado de [buenas prácticas](https://github.com/midudev/la-velada-web-oficial/blob/main/CONTRIBUTING.md#buenas-pr%C3%A1cticas-)
- [X] He revisado localmente los cambios para asegurarme de que no haya errores ni problemas.
- [X] He probado estos cambios en múltiples dispositivos y navegadores para asegurarme de que la landing page se vea y funcione correctamente.
- [X] He actualizado la documentación, si corresponde.

## Impacto potencial

## Contexto adicional

## Enlaces útiles

- Documentación del proyecto: 
- Código de referencia:

2024-04-05 19:56 UTC, lucas-labs commented
@AlejandroSuero Safari creo que no reproduce automáticamente ningún video si está en modo low power (o ahooro de energía). Será por eso que no te funciona en Safari?

2024-04-05 19:58 UTC, lucas-labs commented
> @AlejandroSuero Safari creo que no reproduce automáticamente ningún video si está en modo low power (o ahooro de energía). Será por eso que no te funciona en Safari?

Aunque ahora que lo pienso, si fuese ese el problema, tampoco debería reproducirse la primera vez...

2024-04-05 20:06 UTC, AlejandroSuero commented
@lucas-labs no ese no es el problema, además me asegurado ahora por si acaso y he conectado también el cargador, pero sigue igual.

Además si recargo la página se reproduce igualmente.

Tampoco cargan las fuentes en local, por algún motivo.

2024-04-05 20:09 UTC, AlejandroSuero commented
He notado que se reduzco el script a esto:

```typescript
<script>
   import { $ } from "@/lib/dom-selector"

   const $bgVideoDiv = $("#bg-video")

  if ($bgVideoDiv) $bgVideoDiv.querySelector("video")?.play()
</script>
```

Tampoco hay diferencia en Chrome, pero en Safari sigue con el mismo problema.

2024-04-05 20:14 UTC, lucas-labs commented
😒 Safari is the new IE6.

Estuve googleando un poco y por ahora la única solución que estoy viendo repetida en distintas fuentes es el `.play()`... pero ya se está haciendo en tu script.

No estoy tan familiarizado con Astro, pero podría llegar a ser que el script solo se esté ejecutando la primera vez? Quizá habría que supeditar el script a algún evento.

2024-04-05 20:18 UTC, AlejandroSuero commented
Creo que puede ser un problema de cómo cachea los recursos Safari:

- localhost:
<img width="816" alt="Screenshot 2024-04-05 at 22 11 57" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/c43ed12c-aa44-4007-affa-cdb20cfe64b8">

> Carga inicial

<img width="816" alt="Screenshot 2024-04-05 at 22 11 38" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/938b37f6-b97a-48ec-9b6b-50086d16ccbc">

> Segunda carga

- lavelada.es:

<img width="816" alt="Screenshot 2024-04-05 at 22 12 22" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/7469aa01-c300-475f-b5aa-80f5f56cfd9c">

> Carga inicial

<img width="816" alt="Screenshot 2024-04-05 at 22 12 38" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/83cd2398-653c-47cb-8ef6-6c8e9c9f9e45">

> Segunda carga

2024-04-05 20:20 UTC, AlejandroSuero commented
> 😒 Safari is the new IE6.
> 
> Estuve googleando un poco y por ahora la única solución que estoy viendo repetida en distintas fuentes es el `.play()`... pero ya se está haciendo en tu script.
> 
> No estoy tan familiarizado con Astro, pero podría llegar a ser que el script solo se esté ejecutando la primera vez? Quizá habría que supeditar el script a algún evento (asegurarse de que el script se ejecute nuevamente al cambiar de página).

Esta es mi primera vez trabajando con Astro también así que no me sé muy bien que eventos habría que tarjetear para conseguirlo.

2024-04-05 20:45 UTC, lucas-labs commented
```js
import { $ } from "@/lib/dom-selector"

const playVideo = () => {
	const $bgVideoDiv = $("#bg-video")

	if ($bgVideoDiv) {
		let video = $bgVideoDiv.querySelector("video")

		if (video) {
			video.play()
		}
	}
}

document.addEventListener("astro:page-load", playVideo)
```

@AlejandroSuero podrías probar el script así? (yo estoy en situación de windows así que no tengo Safari 😅, por desgracia o por suerte)

Creo que lo que puede estar pasando es que en tu script actual, estás tomando la referencia del `#bg-video` por fuera de la función del evento.

En el script de arriba lo vuelvo a tomar cada vez que se dispare el evento. 

Seguramente la referencia al video que estamos haciéndo `.play()` es al video anterior.

2024-04-05 21:13 UTC, AlejandroSuero commented
@lucas-labs he probado a hacer eso pero sigue el mismo resultado 😥.

> PD: yo también tengo Windows pero mi portátil de trabajo es un Mac, aunque prefiero Linux antes que Mac, menos restricciones xD.

2024-04-05 22:58 UTC, yurigo commented
Hay varios problemas con el reproductor de video.

- En chrome todo bien.
- En firefox sólo se reproduce el primer video y luego nada
- En safari sólo se reproduce el primer video y luego nada (muy parecido al caso de firefox)
- En safari ios el video se reproduce en pantalla completa

El caso más facil es el de ios: video tiene un atributo `playsinline` que lo soluciona.

En safari se puede solucionar en lugar de trabajar con el src de source, trabajar con el src de video... (no me preguntes 🙈)

En firefox hay un problema con las transition view.  Si se quiere que en firefox funcione hay que descartar la view transition de combates a combate

2024-04-05 23:13 UTC, AlejandroSuero commented
El último commit soluciona:

- [X] Safari
  - [X] iOS
- [X] Chrome
- [X] Brave
- [ ] Firefox

En relación con Firefox:

Si se recarga la página estando en `/combates/[id]` reproduce el vídeo.

Carga inicial sin recargar:
<img width="1658" alt="Screenshot 2024-04-06 at 01 08 32" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/6a92de24-49ff-418c-a759-5531f418e515">

Carga recargando `/combates/[id]`
<img width="1658" alt="Screenshot 2024-04-06 at 01 09 14" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/00a47697-4a0e-48c1-9efc-23f5bc49caca">

2024-04-05 23:21 UTC, yurigo commented
Firefox no está llevando muy bien el tema de view-transitions...  He hecho una pr a tu fork con los cambios que he ido mencionando.  Puedes mirar los cambios en cada commit para ir solucionando los problemas.

En el caso de firefox he eliminado los atributos de `transition:name` en ambas páginas `combates/index.astro` y `combates/[id].astro` para deshabilitar la view-transicion entre esas páginas.

De este modo, firefox hace todo el ciclo de load de la página y va a buscar el video...

2024-04-05 23:24 UTC, AlejandroSuero commented
@yurigo ahora ya funciona, gracias.

Voy a ver si meto un poco de lógica para detectar si es firefox y añadir o no las view transitions y si no funciona o se rompe pues se queda así.

2024-04-06 00:00 UTC, AlejandroSuero commented
@yurigo @lucas-labs creo que ahora ya funciona en todos, al menos lo he probado en: Firefox, Safari, Safari iOS, Google Chrome, Brave.

Si veis algo que falla, decídmelo.

2024-04-06 00:18 UTC, yurigo commented
@AlejandroSuero Estaba explorando otro camino para solucionar esto de las view transitions para firefox sin necesidad de consultar si es firefox o no.

He hecho lo siguiente:

He hecho un revert del commit que eliminaba las `transition:name` por lo que 

- `combates/index.astro`
```diff
	height={combatData.titleSize[1]}
+	transition:name={`title-image-${combat.id}`}
	loading={index < 2 ? "eager" : "lazy"}
```

- `combates/[id].astro`
```diff
	height={imageHeight}
+	transition:name={`title-image-${id}`}
	loading={"eager"}
```

Y después, en `BackgroundVideo.astro` he añadido lo siguiente:
```diff
<div class="fixed left-0 top-0 -z-10 aspect-video h-[100vh] w-screen" id="bg-video">
	<video
+		id="video-player"
		muted
		loop
		class="aspect-video size-full overflow-hidden object-cover opacity-0 transition-opacity duration-500"
		style="mask-image: linear-gradient(to bottom, rgba(0,0,0,1) 70%, transparent);"
		oncanplay="this.classList.add('opacity-70')"
		playsinline
		src={url}
	>
		<source type="video/mp4" src={url} />
	</video>
</div>

+<script is:inline>
+	document.getElementById("video-player").load()
+</script>
```

2024-04-06 00:20 UTC, yurigo commented on src/pages/combates/index.astro
> +											width={combatData.titleSize[0]}
¿no falta añadir ```transition:name={`title-image-${combat.id}`}``` ?

2024-04-06 01:12 UTC, AlejandroSuero commented on src/pages/combates/index.astro
> +											width={combatData.titleSize[0]}
Sí, ya lo he añadido, que parece ser que no guarde ese cambio antes de subir el commit.

2024-04-06 01:33 UTC, AlejandroSuero commented on src/lib/browser.ts
Esto es porque `InstallTrigger`, es específico de **Firefox** y no podía usar `navigator.userAgent` (supongo que por ser *server side*

2024-04-11 18:11 UTC, byMagg commented
A mi me pasa en Chrome

https://github.com/midudev/la-velada-web-oficial/assets/44727429/70499a95-85d7-4119-ac9a-c1be442fb8c2

2024-04-11 19:04 UTC, AlejandroSuero commented
@byMagg en teoría si clonas mi [repo](https://github.com/AlejandroSuero/la-velada-web-oficial), haces `git switch feature/fix-background-video-playing`, instalas las dependecias y lo corres en local, debería estar arreglado.

Cuando se mergee ya estará en la principal.

2024-04-12 09:28 UTC, AlejandroSuero commented
@midudev ya he quitado el código de Firefox en 96060e9 y he comprobado que funcionase.

https://github.com/midudev/la-velada-web-oficial/assets/71392160/da68d152-9eba-4dff-9f9f-ecfbfe614b6f

2024-04-12 10:00 UTC, yurigo commented
En el último commit (el que elimina el código de detección de firefox) has eliminado de `/combates/index.astro` la línea de ```transition:name={`title-image-${combat.id}`}```.  Los exploradores que sí hacen view-transitions pierden esa feature.

2024-04-12 10:03 UTC, yurigo requested changes

2024-04-12 10:03 UTC, yurigo commented on src/pages/combates/index.astro
> -										transition:name={`title-image-${combat.id}`}
ojo! esta línea debería mantenerse

2024-04-12 10:12 UTC, AlejandroSuero commented on src/pages/combates/index.astro
> -										transition:name={`title-image-${combat.id}`}
Lo he añadido en e4232a9 que creo que borré el que no era.

Gracias por darte cuenta 🫡

2024-04-21 06:26 UTC, Jesus-Rojas approved these changes

2024-05-17 20:09 UTC, merged